# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3cb8e3d6ec6b310c27f43176745ff36ded8954cc87f3ba2111296b72cd069ec4b6b7fca314f0a7acc6c11f5d061813f35ccd0a0f8a7e02f33a69d5e4fbd148d0

test:
  secret_key_base: 64c564f205af07483ed2bcbda633783a769326b635da61c936f046a28aa3d9da10910eb9eb73f55634a63b72a91238340cab2a040b1a6a06153e0814aa8623d0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
